spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
jwt:
  secret: "MySuperSecretKeyThatShouldBeLongAndBase64Encoded1234567890"
  expiration: 86400000
logging:
  level:
    org.springframework.security: INFO
